# Generated by Django 5.0.1 on 2024-02-03 09:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='short_intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
