# Generated by Django 5.0.1 on 2024-02-03 09:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_short_intro'),
        ('wagtail_links', '0007_auto_20200101_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='facebook_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_link', to='wagtail_links.link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facebook_url',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_url',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_url',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
