# Generated by Django 5.0.1 on 2024-02-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_facebook_link_homepage_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='linkedin_url',
        ),
    ]
