# Generated by Django 5.0.1 on 2024-02-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_facebook_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='facebook_link',
        ),
    ]
