# Generated by Django 5.0.1 on 2024-02-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_facebook_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
