# Generated by Django 5.0.1 on 2024-02-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='url',
            new_name='facebook_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
