# Generated by Django 5.0.1 on 2024-02-03 10:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_url_homepage_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='greeting',
            field=wagtail.fields.RichTextField(default='Hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
