# Generated by Django 5.0.1 on 2024-02-03 11:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_greeting_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='name',
            field=wagtail.fields.RichTextField(default='shanath'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='roles',
            field=wagtail.fields.RichTextField(default='Developer'),
            preserve_default=False,
        ),
    ]
