# Generated by Django 5.0.1 on 2024-02-03 11:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_name_homepage_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='roles',
            new_name='role1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='role2',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='role3',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
