# Generated by Django 5.0.1 on 2024-02-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_findme'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
