# Generated by Django 5.0.1 on 2024-02-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_findme_socialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
