# Generated by Django 5.0.1 on 2024-02-04 14:47

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_homepage_years_of_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='greeting',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name',
            field=wagtail.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='role1',
            field=wagtail.fields.RichTextField(default=''),
        ),
    ]
