# Generated by Django 5.0.1 on 2024-02-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_protfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protfolio',
            old_name='liked',
            new_name='likes',
        ),
    ]
