# Generated by Django 5.0.1 on 2024-02-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_liked_protfolio_likes'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='protfolio',
            new_name='portfolio',
        ),
    ]
