# Generated by Django 5.0.1 on 2024-02-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_portfolio_portfoliopage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioPage',
        ),
    ]
