# Generated by Django 5.0.1 on 2024-02-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_portfoliopage'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioPage',
            new_name='HomePortfolioPage',
        ),
    ]
