# Generated by Django 5.0.1 on 2024-02-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_portfoliopage_homeportfoliopage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePortfolioPage',
        ),
    ]
