# Generated by Django 5.0.1 on 2024-02-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_portfoliopage'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioPage',
            new_name='Portfolios',
        ),
    ]
