# Generated by Django 5.0.1 on 2024-02-05 09:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='university_address',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
