# Generated by Django 5.0.1 on 2024-02-05 09:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_education_university_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
