# Generated by Django 5.0.1 on 2024-02-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_education_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='description',
            new_name='about',
        ),
    ]
