# Generated by Django 5.0.1 on 2024-02-05 09:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_rename_description_education_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='about',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
