# Generated by Django 5.0.1 on 2024-02-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_education_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='about',
            new_name='about_university',
        ),
    ]
