# Generated by Django 5.0.1 on 2024-02-05 09:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_rename_about_education_about_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='about_university',
            field=wagtail.fields.RichTextField(),
        ),
    ]
