# Generated by Django 5.0.1 on 2024-02-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_education_about_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='about_university',
        ),
    ]
