# Generated by Django 5.0.1 on 2024-02-05 17:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='page',
            field=modelcluster.fields.ParentalKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='home.homepage'),
            preserve_default=False,
        ),
    ]
