# Generated by Django 5.0.1 on 2024-02-05 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_professional_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='how_much_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
