# Generated by Django 5.0.1 on 2024-02-07 03:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='language',
            field=wagtail.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
