# Generated by Django 5.0.1 on 2024-02-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_clients_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
