# Generated by Django 5.0.1 on 2024-02-07 04:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_clients'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_name',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_url',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='language',
            field=wagtail.fields.RichTextField(),
        ),
    ]
