# Generated by Django 5.0.1 on 2024-02-07 04:25

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_clients_client_name_alter_clients_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_url',
            field=wagtail.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='language',
            field=wagtail.fields.RichTextField(default='all'),
            preserve_default=False,
        ),
    ]
