# Generated by Django 5.0.1 on 2024-02-07 11:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_alter_clients_client_logo_alter_clients_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='phone',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
